# Generated by Django 4.2.1 on 2023-06-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_weight_and_reps_weight_alter_weight_and_reps_reps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
