# Generated by Django 4.2.1 on 2023-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_delete_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight_and_reps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
