# Generated by Django 4.2.1 on 2023-06-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_workouts_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workouts',
        ),
    ]
