# Generated by Django 4.2.1 on 2023-06-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_weight_and_reps_max_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight_and_reps',
            name='max_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
