# Generated by Django 4.2.1 on 2023-06-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_rename_exercises_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_split',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
