# Generated by Django 4.2.1 on 2023-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workout_split_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_split',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
