# Generated by Django 4.2.1 on 2023-06-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workout_split_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.ManyToManyField(to='workouts.exercise'),
        ),
    ]
