# Generated by Django 4.2.1 on 2023-06-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_remove_workout_name_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
    ]
