# Generated by Django 4.2.1 on 2023-06-20 03:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_number_workout_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=0, size=None),
        ),
    ]
