# Generated by Django 4.2.1 on 2023-06-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_remove_workout_reps_delete_number_workout_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.TextField(),
        ),
    ]
