# Generated by Django 4.2.1 on 2023-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_split',
            name='reps',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
