# Generated by Django 4.2.1 on 2023-06-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_workout_split_reps_delete_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_split',
            name='reps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
